### ISSUE TITLE
Implement the DTW(Dynamic Time Warpping) algorithm into compilable code

### ISSUE THREAD

**Issue by hwen3** [CMPUT414W15/LEAP#11]
A skeletal pseudo code already exists in a paper and should be transferred over into our python scripts. However, the pseudo code provided need some potential adjustments to work properly.

**Comment by hwen3** [comment]
Various implementations of DTW in python libraries were found and thus can be included in our projects
- Machine learning python(mlpy): [http://mlpy.sourceforge.net/]
- Dynamic Time Warping project (DTW R): [http://dtw.r-forge.r-project.org/]

**Comment by aktse** [comment]
Found a better script that we can use...provided we can get MB to accept numpy

http://nbviewer.ipython.org/github/pierre-rouanet/dtw/blob/master/simple%20example.ipynb
